[package]
name = "bergloom-example"
version = "0.1.0"
edition = "2024"

[dependencies]
bergloom-core = { workspace = true }
iceberg = { workspace = true }
iceberg-catalog-memory = { workspace = true }
parquet = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
