[workspace]
resolver = "2"
members = ["core", "codegen", "services/compactor"]

[workspace.dependencies]
# Async runtime and utilities
async-stream = "0.3.5"
async-trait = "0.1.86"
futures = "0.3.17"
futures-async-stream = "0.2.9"
tokio = { version = "1", default-features = false}

# Data processing and storage
iceberg = { git = "https://github.com/risingwavelabs/iceberg-rust.git", rev = "e026f860432bbdacfa282b9d72b501230ce5ea22", features = [
    "storage-s3",
    "storage-gcs",
] }
parquet = { version = "54", features = ["async"] }

# gRPC and Protocol Buffers
prost = "0.12"
tonic = "0.11.0"

# Serialization
serde = { version = "1", features = ["rc"] }
serde_with = { version = "3", features = ["json"] }
serde_json = { version = "1"}

# Error handling
thiserror = "2.0.11"

# Utilities
url = "2"

# Local workspace members
bergloom-core = { path = "./core" }
bergloom-codegen = { path = "./codegen" }
bergloom-service-compactor = { path = "./services/compactor" }
